spring:
  application:
    name: pokemon-team-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/poketeam
    username: poke
    password: poke

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
